name: Setup
description: Sets up the job
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      with:
        bun-version: 1.0.27
    - name: Install dependencies
      shell: bash
      run: bun install
