name: Setup
description: Sets up the job
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1.1.1
      with:
        bun-version: 1.0.27
    - name: Install dependencies
      shell: bash
      run: bun install
