# Reusable Build Workflow
name: _Build

on:
  workflow_call:

jobs:
  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: bun run compile

      - name: Cache compiled extension
        uses: actions/cache@v4
        with:
          path: out/
          key: compiled-extension-${{ github.sha }}