name: 🧪 Integrate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  quality:
    name: Quality
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2
      - name: Run Biome checks
        run: biome ci --reporter=github
      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          cache: true
          run_install: true
      - name: Typecheck
        run: pnpm run typecheck
  
  build:
    name: Build
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          cache: true
          run_install: true
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: '.node-version'
      - name: Build
        run: pnpm run build
      - name: Package
        run: pnpm package