name: 🧪 Integrate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  quality:
    name: Quality
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
      - name: Run Biome checks
        run: biome ci --reporter=github
      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          run_install: true
      - name: Typecheck
        run: pnpm run typecheck
  
  build:
    name: Build
    runs-on: depot-ubuntu-24.04-arm-16
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          run_install: true
      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.node-version'
      - name: Build
        run: pnpm run build
      - name: Package
        run: pnpm package