name: 🚀 Release new stable version

on: [workflow_dispatch]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: .node-version
      - name: Setup PNPM
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          run_install: true
      - name: Consume changesets
        run: pnpm changeset version
      - name: Retrieve updated version
        id: version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Commit, tag, and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): v${{ steps.version.outputs.version }}"
          git tag -a v${{ steps.version.outputs.version }} -m "v${{ steps.version.outputs.version }}"
          git push --follow-tags
      - name: Build extension
        run: pnpm run build
      - name: Package pre-release extension
        run: pnpm vsce package --pre-release -o biome.vsix
      - name: Publish to Visual Studio Marketplace
        run: pnpm vsce publish --packagePath biome.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to Open VSX Registry
        run: pnpm exec ovsx publish --packagePath biome.vsix
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
      