name: 🚀 Release new stable version

on: [workflow_dispatch]

jobs:

  publish:
    name: Publish
    runs-on: depot-ubuntu-24.04-arm-16
    permissions: 
      contents: write
      packages: write
      statuses: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .node-version
      - name: Setup PNPM
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          run_install: true
      - name: Consume changesets
        run: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve updated version
        id: version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Commit, tag, and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .changeset package.json CHANGELOG.md
          git commit -m "chore(release): v${{ steps.version.outputs.version }}"
          git tag -a v${{ steps.version.outputs.version }} -m "v${{ steps.version.outputs.version }}"
          git push --follow-tags
      - name: Build extension
        run: pnpm run build
      - name: Package stable extension
        run: pnpm vsce package -o biome.vsix
      - name: Publish to Visual Studio Marketplace
        run: pnpm vsce publish --packagePath biome.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to Open VSX Registry
        run: pnpm exec ovsx publish --packagePath biome.vsix
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
      