# This workflow is responsible for releasing a new stable version of the 
# extension. It is meant to be triggered manually and will automatically
# determine the next version number based on the commit history, which it will
# use to create a new tag. Publication of the new version will be handled by
# the `publish-stable.yaml` workflows.

name: 🚀 Release new stable version

on:
  workflow_dispatch:

jobs:
  tag:
    name: Tag stable
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      version: ${{ steps.next-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          # Fetch the whole history so we can determine the next version number
          # based on the commit history.
          fetch-depth: 0
      - name: Setup Biome
        uses: biomejs/setup-biome@1cbe33ead22c7a2fded3b52fa2893611c815c9b5 # v2
      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@2778609c643a39a2576c4bae2e493b855eb4aee8 # v2
      - name: Determine next version
        id: next-version
        run: |
         version="$(git-cliff --bumped-version --config .git-cliff/release-notes.toml 2>/dev/null)"
         echo "version=${version:1}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Patch package.json version with stable identifier
        run: |
          jq \
            --arg version "${{ steps.next-version.outputs.version }}" \
            --tab '.version = $version' \
            package.json > package.json.tmp \
            && mv package.json.tmp package.json
          biome format --write package.json
      - name: Generate changelog
        run: |
          git-cliff \
            --config .git-cliff/changelog.toml \
            --tag v${{ steps.next-version.outputs.version }} \
            > CHANGELOG.md 5014d9d9291a7de6c11afbe154ce73225c45aefb..
      - name: Commit, tag, and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): v${{ steps.next-version.outputs.version }}"
          git tag -a v${{ steps.next-version.outputs.version }} -m "v${{ steps.next-version.outputs.version }}"
          git push --follow-tags

  publish:
    name: Publish
    needs: [tag]
    uses: ./.github/workflows/~publish-stable.yaml
    secrets: inherit
    with:
      version: ${{ needs.tag.outputs.version }}