# This workflow is responsible for packaging the extension as a VSIX artifact
# for the nightly release.
name: ~Package nightly release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Build
        run: pnpm run build
      - name: Patch package.json version with nightly identifier
        run: |
          jq \
            --arg version "${{ inputs.version }}" \
            --tab '.version = $version' \
            package.json > package.json.tmp \
            && mv package.json.tmp package.json
      - name: Package VSIX
        run: pnpm vsce package --pre-release -o biome.vsix
      - name: Upload the artifact
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: biome.vsix
          path: biome.vsix